### ISSUE TITLE
~/GameAISDK/tools/AIClient$ python demo.py 运行出错

### ISSUE THREAD

**Issue by lsqtzj** [Tencent/GameAISDK#13]
Ubuntu 20.4 
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from aiclient.start_service import ActionExecute
ImportError: bad magic number in 'aiclient': b'3\r\r\n'

**Comment by dijinzhou** [comment]
python版本不匹配引起的。可以加技术QQ群讨论：1095989343

**Comment by bothe1989** [comment]
Traceback (most recent call last):
  File "D:\git\GameAISDK\tools\AIClient\demo.py", line 10, in <module>
    from aiclient.start_service import ActionExecute
ImportError: No module named aiclient.start_service
看了下工程目录结构确实没有这个

**Comment by 836304831** [comment]
AIClient如果下载完整的话，是有aiclient.start_service这个module的，先判断一下代码是否全部拉取到了，也可以贴一下AIClient的目录展开的截图，便于协助你排查问题。

**Comment by EdwardCheck** [comment]
> AIClient如果下载完整的话，是有aiclient.start_service这个module的，先判断一下代码是否全部拉取到了，也可以贴一下AIClient的目录展开的截图，便于协助你排查问题。

![image](https://user-images.githubusercontent.com/25213289/108933749-a4f2c180-7686-11eb-8d5c-7ec6abde6c54.png)
AIClient都是.pyc文件，导入提示ImportError: bad magic number in 'aiclient': b'3\r\r\n'

**Comment by 836304831** [comment]
1. 如果使用docker镜像方式，即使是在window下，也要下载ubtunu的编译版本。因为docker镜像是基于ubuntu的。
2. 编译的版本windows支持python3.6,ubuntu下支持python3.5，确认一下python版本。
