### ISSUE TITLE
远程主机关闭了一个已经建立的链接

### ISSUE THREAD

**Issue by fooSynaptic** [Tencent/GameAISDK#20]
你好 我在跑demo的过程中当运行sdkTool `python main.py`的时候不断报错关闭了建立的连接
我是使用mac安装的win环境运行的项目
```
(py3) C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool>python main.py
libpng warning: iCCP: known incorrect sRGB profile
 [37m[INFO] [0m Android deviceID is None ( [1mAndroidGameDevice.py [0m:37)
[2020-12-25 15:34:35,186][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\gamedevice\AndroidGameDevice.py:37][ [37m[INFO] [0m] : Android deviceID is None
[2020-12-25 15:34:35,186][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\gamedevice\AndroidGameDevice.py:37][ [37m[INFO] [0m] : Android deviceID is None
 [37m[INFO] [0m platform getinstance ( [1mWrappedPlatform.py [0m:29)
[2020-12-25 15:34:35,186][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\devicePlatform\WrappedPlatform.py:29][ [37m[INFO] [0m] : platform getinstance
[2020-12-25 15:34:35,186][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\devicePlatform\WrappedPlatform.py:29][ [37m[INFO] [0m] : platform getinstance
 [37m[INFO] [0m platform init ( [1mWrappedPlatform.py [0m:34)
[2020-12-25 15:34:35,217][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\devicePlatform\WrappedPlatform.py:34][ [37m[INFO] [0m] : platform init
[2020-12-25 15:34:35,217][C:\Users\justwe\Desktop\GameAISDK-KPXYX\GameAISDK\GameAISDK\tools\SDKTool\libs\WrappedDeviceAPI\devicePlatform\WrappedPlatform.py:34][ [37m[INFO] [0m] : platform init
 [37m[INFO] [0m adi=arm64-v8a, sdk=29 ( [1mInitializer.py [0m:39)
[2020-12-25 15:34:35,436][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:39][ [37m[INFO] [0m] : adi=arm64-v8a, sdk=29
 [37m[INFO] [0m standalone:1 ( [1mPlatformWeTest.py [0m:80)
[2020-12-25 15:34:35,482][D:\workspace\github\modify\PlatformWeTest\demo\PlatformWeTest.py:80][ [37m[INFO] [0m] : standalone:1
 [37m[INFO] [0m Install touch server... ( [1mInitializer.py [0m:44)
[2020-12-25 15:34:35,592][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:44][ [37m[INFO] [0m] : Install touch server...
 [37m[INFO] [0m adi=arm64-v8a, sdk=29 ( [1mInitializer.py [0m:39)
[2020-12-25 15:34:35,592][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:39][ [37m[INFO] [0m] : adi=arm64-v8a, sdk=29
 [37m[INFO] [0m Push touch server to device ( [1mInitializer.py [0m:51)
[2020-12-25 15:34:35,592][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:51][ [37m[INFO] [0m] : Push touch server to device
 [37m[INFO] [0m Install touch server complete ( [1mInitializer.py [0m:55)
[2020-12-25 15:34:35,827][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:55][ [37m[INFO] [0m] : Install touch server complete
 [37m[INFO] [0m Install cloud screen... ( [1mInitializer.py [0m:62)
[2020-12-25 15:34:35,842][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:62][ [37m[INFO] [0m] : Install cloud screen...
 [37m[INFO] [0m adi=arm64-v8a, sdk=29 ( [1mInitializer.py [0m:39)
[2020-12-25 15:34:35,842][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:39][ [37m[INFO] [0m] : adi=arm64-v8a, sdk=29
 [37m[INFO] [0m Push cloudscreen to device ( [1mInitializer.py [0m:73)
[2020-12-25 15:34:35,905][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:73][ [37m[INFO] [0m] : Push cloudscreen to device
 [37m[INFO] [0m Install cloud screen complete ( [1mInitializer.py [0m:77)
[2020-12-25 15:34:36,170][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:77][ [37m[INFO] [0m] : Install cloud screen complete
 [37m[INFO] [0m Install input server... ( [1mInitializer.py [0m:84)
[2020-12-25 15:34:36,170][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:84][ [37m[INFO] [0m] : Install input server...
 [37m[INFO] [0m Install input server complete ( [1mInitializer.py [0m:96)
[2020-12-25 15:34:36,420][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:96][ [37m[INFO] [0m] : Install input server complete
 [37m[INFO] [0m inputserver run begin... ( [1mInitializer.py [0m:125)
[2020-12-25 15:34:36,623][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:125][ [37m[INFO] [0m] : inputserver run begin...
 [37m[INFO] [0m cloudscreen run begin... ( [1mInitializer.py [0m:142)
[2020-12-25 15:34:36,623][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:142][ [37m[INFO] [0m] : cloudscreen run begin...
 [31m[ERROR] [0m cloudscreen run over, return value:255 ( [1mInitializer.py [0m:149)
 [31m[ERROR] [0m inputserver run over, return value:1 ( [1mInitializer.py [0m:132)
[2020-12-25 15:34:37,655][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:149][ [31m[ERROR] [0m] : cloudscreen run over, return value:255
[2020-12-25 15:34:37,655][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:132][ [31m[ERROR] [0m] : inputserver run over, return value:1
 [37m[INFO] [0m cloudscreen run begin... ( [1mInitializer.py [0m:142)
 [37m[INFO] [0m inputserver run begin... ( [1mInitializer.py [0m:125)
[2020-12-25 15:34:38,686][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:142][ [37m[INFO] [0m] : cloudscreen run begin...
[2020-12-25 15:34:38,686][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:125][ [37m[INFO] [0m] : inputserver run begin...
 [31m[ERROR] [0m inputserver run over, return value:1 ( [1mInitializer.py [0m:132)
 [31m[ERROR] [0m cloudscreen run over, return value:255 ( [1mInitializer.py [0m:149)
[2020-12-25 15:34:39,718][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:132][ [31m[ERROR] [0m] : inputserver run over, return value:1
[2020-12-25 15:34:39,718][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:149][ [31m[ERROR] [0m] : cloudscreen run over, return value:255
 [37m[INFO] [0m cloudscreen run begin... ( [1mInitializer.py [0m:142)
 [37m[INFO] [0m inputserver run begin... ( [1mInitializer.py [0m:125)
[2020-12-25 15:34:40,748][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:142][ [37m[INFO] [0m] : cloudscreen run begin...
[2020-12-25 15:34:40,748][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:125][ [37m[INFO] [0m] : inputserver run begin...
 [37m[INFO] [0m input thread started ( [1mPlatformWeTest.py [0m:97)
[2020-12-25 15:34:40,764][D:\workspace\github\modify\PlatformWeTest\demo\PlatformWeTest.py:97][ [37m[INFO] [0m] : input thread started
 [37m[INFO] [0m cloudscreen thread started ( [1mPlatformWeTest.py [0m:105)
[2020-12-25 15:34:40,764][D:\workspace\github\modify\PlatformWeTest\demo\PlatformWeTest.py:105][ [37m[INFO] [0m] : cloudscreen thread started
 [37m[INFO] [0m connect 127.0.0.1:1111 ( [1mTcpSocketHandler.py [0m:231)
[2020-12-25 15:34:40,779][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:231][ [37m[INFO] [0m] : connect 127.0.0.1:1111
 [37m[INFO] [0m connect 127.0.0.1:1113 ( [1mTcpSocketHandler.py [0m:231)
[2020-12-25 15:34:40,795][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:231][ [37m[INFO] [0m] : connect 127.0.0.1:1113
 [37m[INFO] [0m set socket option ( [1mTcpSocketHandler.py [0m:235)
 [37m[INFO] [0m set socket option ( [1mTcpSocketHandler.py [0m:235)
[2020-12-25 15:34:40,811][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:235][ [37m[INFO] [0m] : set socket option
[2020-12-25 15:34:40,811][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:235][ [37m[INFO] [0m] : set socket option
 [37m[INFO] [0m set event ( [1mTcpSocketHandler.py [0m:260)
 [37m[INFO] [0m set event ( [1mTcpSocketHandler.py [0m:260)
[2020-12-25 15:34:40,826][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:260][ [37m[INFO] [0m] : set event
[2020-12-25 15:34:40,826][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:260][ [37m[INFO] [0m] : set event
 [31m[ERROR] [0m cloudscreen run over, return value:255 ( [1mInitializer.py [0m:149)
[2020-12-25 15:34:41,779][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:149][ [31m[ERROR] [0m] : cloudscreen run over, return value:255
 [31m[ERROR] [0m inputserver run over, return value:1 ( [1mInitializer.py [0m:132)
[2020-12-25 15:34:41,779][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:132][ [31m[ERROR] [0m] : inputserver run over, return value:1
 [37m[INFO] [0m get_device_info: timeout=60 ( [1mPlatformWeTest.py [0m:149)
 [37m[INFO] [0m cloudscreen run begin... ( [1mInitializer.py [0m:142)
[2020-12-25 15:34:42,795][D:\workspace\github\modify\PlatformWeTest\demo\PlatformWeTest.py:149][ [37m[INFO] [0m] : get_device_info: timeout=60
[2020-12-25 15:34:42,795][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:142][ [37m[INFO] [0m] : cloudscreen run begin...
 [31m[ERROR] [0m get_display_info: err=0, packet=None ( [1mPlatformWeTest.py [0m:319)
[2020-12-25 15:34:42,795][D:\workspace\github\modify\PlatformWeTest\demo\PlatformWeTest.py:319][ [31m[ERROR] [0m] : get_display_info: err=0, packet=None
 [37m[INFO] [0m inputserver run begin... ( [1mInitializer.py [0m:125)
[2020-12-25 15:34:42,795][D:\workspace\github\modify\PlatformWeTest\demo\Initializer.py:125][ [37m[INFO] [0m] : inputserver run begin...
 [31m[ERROR] [0m read packet exception ( [1mTcpSocketHandler.py [0m:188)
Traceback (most recent call last):
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 159, in run
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 350, in read_packet
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 72, in read_packet_bytes
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 58, in __read_bytes
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2020-12-25 15:34:42,795][D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py:188][ [31m[ERROR] [0m] : read packet exception
Traceback (most recent call last):
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 159, in run
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 350, in read_packet
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 72, in read_packet_bytes
  File "D:\workspace\github\modify\PlatformWeTest\demo\TcpSocketHandler.py", line 58, in __read_bytes
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

**Comment by ssyan1** [comment]
我也遇到这个问题了，请问找到原因了吗？

**Comment by shineway14** [comment]
请问这个是跟安卓版本有关吗，我也碰到这个问题。我的华为mate30@sinshen ,请问这个什么原因

**Comment by bujinjinyaonuli** [comment]
我也遇到了这样的问题，请问楼主解决了吗？如有解决方案希望联系QQ：643429173
