### ISSUE TITLE
pip install -r requirements.txt安装依赖报错

### ISSUE THREAD

**Issue by l1046j** [Tencent/GameAISDK#24]
ERROR: Could not find a version that satisfies the requirement torch==1.3.0+cpu
ERROR: No matching distribution found for torch==1.3.0+cpu

pip 21.0.1
python 3.6.2

请问下如何解决呢？感谢

**Comment by 836304831** [comment]
手动安装一下呢:
pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by l1046j** [comment]
多谢，上面的问题ok了。python main.py  点击start test 又报这个错：start service test_node successprocess python agentai.py --mode=test --cfgpath=D:/GameAISDK/tools/SDKTool/project/TTKP/TTKP.prj start failed, service_name: test_node error: []phone_client_process failed   用命令行执行agentai.py 报错：
[2021-04-29 16:06:37,298][agentai.py:135][ERROR] : exception: No module named 'tensorflow.python.keras.applications.resnet50' msg: Traceback (most recent call last):
  File "agentai.py", line 131, in Main
    RunFrameWork(args.mode)
  File "agentai.py", line 92, in RunFrameWork
    if aiFramework.Init() is True:
  File "../src/AgentAI/aiframework\AIFrameWork.py", line 59, in Init
    if self._InitAIObject() is True:
  File "../src/AgentAI/aiframework\AIFrameWork.py", line 73, in _InitAIObject
    self.__agentEnv = self.__aiPlugin.CreateAgentEnvObj()
  File "../src/AgentAI/aiframework\AIPlugin.py", line 235, in CreateAgentEnvObj
    envPackage = __import__(modulename)
  File "../src/AgentAI/agentenv\ImitationEnv.py", line 16, in <module>
    from aimodel.ImitationLearning.MainImitationLearning import MainImitationLearning
  File "../src/AgentAI/aimodel\ImitationLearning\MainImitationLearning.py", line 16, in <module>
    from .Network import Network
  File "../src/AgentAI/aimodel\ImitationLearning\Network.py", line 21, in <module>
    from tensorflow.python.keras.applications.resnet50 import conv_block, identity_block
ModuleNotFoundError: No module named 'tensorflow.python.keras.applications.resnet50'

**Comment by 836304831** [comment]
安装好tensorflow之后，在终端输入python
然后执行：from tensorflow.python.keras.applications.resnet50 import conv_block, identity_block
确认tensorflow的版本，应该是版本不对。如果之前安装了就不会卸载在安装。
