### ISSUE TITLE
想问一下，缺少tbus，这个tbus是什么 我在百度上也没找到，尝试用pip安装也没有找到

### ISSUE THREAD

**Issue by Octopus-Monster** [Tencent/GameAISDK#31]
PS C:\Users\zhangyu> python -u "g:\AIgameTest\GameAISDK\tools\SDKTool\main.py"
Traceback (most recent call last):
  File "g:\AIgameTest\GameAISDK\tools\SDKTool\main.py", line 21, in <module>
    from src.ui.main_window.tool_main_window import SDKMainWindow
  File "g:\AIgameTest\GameAISDK\tools\SDKTool\src\ui\main_window\tool_main_window.py", line 20, in <module>
    from ...ui.debug.debug_factory import DebugFactory
    from .game_reg_debug import GameRegDebug
  File "g:\AIgameTest\GameAISDK\tools\SDKTool\src\ui\debug\game_reg_debug.py", line 22, in <module>
    from ...communicate.agent_api_mgr import AgentAPIMgr, MSG_SEND_GROUP_ID, GAME_RESULT_INFO
  File "g:\AIgameTest\GameAISDK\tools\SDKTool\src\communicate\agent_api_mgr.py", line 15, in <module>
    from .agent_msg_mgr import MsgMgr, MSG_SEND_TASK_CONF, MSG_SEND_GROUP_ID, MSG_SEND_TASK_FLAG, MSG_SEND_ADD_TASK, \
  File "g:\AIgameTest\GameAISDK\tools\SDKTool\src\communicate\agent_msg_mgr.py", line 27, in <module>
    import tbus
ModuleNotFoundError: No module named 'tbus'
PS C:\Users\zhangyu> pip install tbus
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tbus (from versions: none)
ERROR: No matching distribution found for tbus

**Comment by 836304831** [comment]
tbus不是外部依赖，tbus是编译生成，通过源码编译会自动生成tbus相关的包。
如果是编译好的，对应的bin目录下是包含tbus相关的依赖的，如果无法正确编译生成，可从官网下载编译好的项目，然后将tbus相关的依赖拷贝过去。

**Comment by aGreatMother** [comment]
后来有解决吗 我一直也是这个问题 能看tbus的 pyd 但是有问题还是
