### ISSUE TITLE
已连接到手机，但一直报错[./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:190][ERROR] : read packet exception

### ISSUE THREAD

**Issue by yuqangy123** [Tencent/GameAISDK#49]
[2023-06-13 16:05:37,233][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:190][ERROR] : read packet exception
Traceback (most recent call last):
  File "./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py", line 160, in run
  File "./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py", line 325, in read_packet
  File "./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py", line 73, in read_packet_bytes
  File "./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py", line 59, in __read_bytes
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2023-06-13 16:05:37,233][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:195][INFO] : reader: put packet MSG_CLOSE_SOCKET
[2023-06-13 16:05:37,234][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:155][DEBUG] : ---wait here
[2023-06-13 16:05:37,234][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:118][INFO] : close socket, clear event
[2023-06-13 16:05:37,234][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:286][INFO] : ############### break here, not flag=True
[2023-06-13 16:05:37,242][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:219][INFO] : set heartEvent
[2023-06-13 16:05:37,243][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:173][DEBUG] : >-- heart beat <--: header {
  sequenceId: 9527
  timestamp: 1686643669379
  command: CLOUDSCREEN_HEARTBEAT_RES
}

**Comment by elric00** [comment]
请问这个tbus是在什么时候安装的？我现在到运行sdktool启动时，tbus并没有被发现，你是否已经启动了sdktool
![Uploading 微信图片_20240815091450.png…]()
